[terminal]
vt = 1

[default_session]
command = '''
tuigreet \
  --cmd sway \
  --power-reboot 'sudo systemctl reboot' \
  --power-shutdown 'sudo systemctl poweroff' \
  --remember \
  --time \
  --user-menu \
  --width 72
'''
user = "greeter"
